# Gov2Biz Load Balancer Services
# AWS Application Load Balancer configuration for external access
# Deploy with: kubectl apply -f loadbalancer-services.yml

---
# Application Load Balancer for Frontend (Public)
apiVersion: v1
kind: Service
metadata:
  name: gov2biz-frontend-lb
  namespace: gov2biz
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "2"
  labels:
    app: mvc-frontend
spec:
  type: LoadBalancer
  selector:
    app: mvc-frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
# Application Load Balancer for API Gateway (Public)
apiVersion: v1
kind: Service
metadata:
  name: gov2biz-api-gateway-lb
  namespace: gov2biz
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "2"
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None

---
# Ingress Controller for Advanced Routing (Alternative to NLB)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gov2biz-ingress
  namespace: gov2biz
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
    alb.ingress.kubernetes.io/success-codes: "200-399"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/tags: Environment=Production,Project=Gov2Biz
spec:
  rules:
  - host: www.gov2biz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mvc-frontend
            port:
              number: 80
  - host: api.gov2biz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
      - path: /api/license
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
      - path: /api/document
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
      - path: /api/notification
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80

---
# Internal Load Balancer for SQL Server (Private - for debugging/management)
apiVersion: v1
kind: Service
metadata:
  name: gov2biz-mssql-internal-lb
  namespace: gov2biz
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: mssql
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
  - name: mssql
    port: 1433
    targetPort: 1433
    protocol: TCP

---
# Network Policy for Database Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mssql-network-policy
  namespace: gov2biz
spec:
  podSelector:
    matchLabels:
      app: mssql
  policyTypes:
  - Ingress
  ingress:
  # Allow only microservices to connect to SQL Server
  - from:
    - podSelector:
        matchLabels:
          app: license-service
    - podSelector:
        matchLabels:
          app: payment-service
    - podSelector:
        matchLabels:
          app: document-service
    - podSelector:
        matchLabels:
          app: notification-service
    ports:
    - protocol: TCP
      port: 1433

---
# Network Policy for Redis Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
  namespace: gov2biz
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  # Allow only specific services to connect to Redis
  - from:
    - podSelector:
        matchLabels:
          app: license-service
    - podSelector:
        matchLabels:
          app: notification-service
    ports:
    - protocol: TCP
      port: 6379

---
# Service Monitor for Prometheus (Optional)
apiVersion: v1
kind: Service
metadata:
  name: gov2biz-metrics
  namespace: gov2biz
  labels:
    app: gov2biz-monitoring
spec:
  selector:
    app: mvc-frontend
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
